# Generated by Django 2.0.7 on 2018-08-08 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20180808_0443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='id',
            new_name='user_role',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='roles',
            new_name='user_role',
        ),
    ]
