# Generated by Django 2.0.7 on 2018-08-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='season_finish',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='season',
            name='season_start',
            field=models.DateField(),
        ),
    ]
