# Generated by Django 2.0.7 on 2018-08-08 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='race',
            old_name='race_date',
            new_name='race_finish',
        ),
        migrations.AddField(
            model_name='race',
            name='race_start',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 8, 11, 53, 56, 737757)),
            preserve_default=False,
        ),
    ]
